# fly.toml app configuration file generated for usamneta00 on 2024-12-01T13:05:19Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'usamneta00'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
